name: Frp Windows

on:
  workflow_dispatch:
  push:
    branches: [ dev ]
jobs:
  run_windows:
    runs-on: windows-latest
    timeout-minutes: 360
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: pwsh
        run: echo "dir=$(npm config get cache)" >> ${env:GITHUB_OUTPUT}

      - uses: actions/cache@v4
        id: npm-cache
        with:
          path: |
            ${{ steps.npm-cache-dir.outputs.dir }}
            C:\Users\cicy-dev\AppData\Roaming\npm
            C:\Users\cicy-dev\AppData\Roaming\npm-cache
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Restore pip cache
        id: cache-pip
        uses: actions/cache@v4
        with:
          path: |
            ~\appdata\local\pip\cache
            C:\Users\cicy-dev\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache project
        id: c-projects
        uses: actions/cache@v4
        with:
          path: c:\projects
          key: c-project
      
      - name: Cache d project
        id: d-projects
        uses: actions/cache@v4
        with:
          path: d:\projects
          key: d-project
      
      - name: Restore Electron app cache
        id: electron-app-cache
        uses: actions/cache@v4
        with:
          path: C:\Users\cicy-dev\AppData\Roaming\Electron
          key: electron-app
      
      - name: Boot
        env:
          FRP_TOKEN: ${{ secrets.FRP_TOKEN }}
          DATA:  ${{ secrets.DATA }}
        run: |
          .\scripts\windows\boot.ps1
        shell: powershell
        
        